
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pyritephp_app
    container_name: pyritephp_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    networks:
      - pyritephp

networks:
  pyritephp:
    driver: bridge